player.exp.toNextLevel=30
inventory.count=5
inventory.item.3.name=OTHER
inventory.item.1.value=1
player.name=PLAYER
inventory.item.2.type=OTHER
player.defense.base=6
inventory.item.2.description=OTHER is a(n) OTHER. It has a value of 6.
inventory.item.1.description=BLASTER is a(n) WEAPON. It has a value of 1.
inventory.item.0.description=OTHER is a(n) OTHER. It has a value of 5.
inventory.item.0.type=OTHER
inventory.item.4.value=1
inventory.item.4.name=OTHER
area.world.number=0
inventory.item.3.value=3
player.health.base=1002
inventory.item.0.name=OTHER
inventory.item.4.type=OTHER
area.y=0
inventory.item.1.type=WEAPON
inventory.item.2.name=OTHER
player.x=379.5001
player.level=2
area.x=2
inventory.item.0.value=5
player.exp.current=25
player.y=225.50005
inventory.item.1.name=BLASTER
inventory.coins.count=6
player.health.current=344
inventory.item.3.type=OTHER
inventory.item.2.value=6
inventory.item.3.description=OTHER is a(n) OTHER. It has a value of 3.
inventory.item.4.description=OTHER is a(n) OTHER. It has a value of 1.
player.attack.base=27
